name: Packer Build on Merge
 
on:
  push:
    branches:
      - main 
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Packer
      uses: hashicorp/setup-packer@main
      with:
        packer-version: '1.7.0' 
    - name: Build with Packer
      run: packer build newtemplate.pkr.hcl
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}